behaviors:
  default:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 256
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 3
    summary_freq: 2000
    threaded: true
    
  Kart:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256 #decreased from 256
      buffer_size: 10240
      learning_rate: 3.0e-4 #decreased from 3e-4
      beta: 5.0e-4 #How much randomness is in the movements
      epsilon: 0.2 #how much new vs old policies can change during training
      lambd: 0.99
      num_epoch: 3 #larger batch size justifies larger, but makes updates more unstable
      learning_rate_schedule: linear #can specify for beta and epsilon but they default to this for their decreasing
    network_settings:
      normalize: true
      hidden_units:  512 #increased from 256
      num_layers: 3 #increased from 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: Demos/JermaHouse2_0.demo
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 2000
    threaded: true

  GoodKart:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 7500000
    time_horizon: 64
    summary_freq: 2000
    threaded: true

